def writesublog(i):
	src = file('Sublog.sh', "w")
	src.write("#!/bin/bash\n")
	src.write("#PBS -l walltime=00:10:00\n")
	src.write("#PBS -l nodes=1:ppn=16\n")
	src.write("#PBS -N %s \n" %i)
	a=findqueue(600,16)
	while(a):
		if(a=='debug' or a=='ncn' or a=='prism' or a=='standby' or a=='strachan'):
			break
		a=findqueue(600,16)
	src.write("#PBS -q %s\n" %a)
	src.write("\n")
	src.write("set echo\n")
	src.write("\n")
	src.write("cd $PBS_O_WORKDIR\n")
	src.write("\n")
	src.write("unzip logresults.zip\n")
	src.write("cp *.dat* logresults\n")
	src.write("cp *.lammps logresults\n")
	src.write("cp *.in logresults\n")
	src.write("cp in.* logresults\n")
	src.write("cp *.txt logresults\n")
	src.write("cp logini.m logresults\n")
	src.write("cp *.sh logresults\n")
	src.write("cp *.reax logresults\n")
	src.write("cd logresults\n")
	src.write("cp *.in x.in\n")
	src.write("cp in.* x.in\n")
	src.write("module load matlab\n")
	src.write("matlab < logini.m > result.m\n")
	src.write("\n")
	src.write("mkdir home\n")
	src.write("cp *.png home\n")
	src.write("cp *.dat* home\n")
	src.write("cp *.in home\n")
	src.write("cp in.* home\n")
	src.write("cp *.lammps home\n")
	src.write("cp *.reax home\n")
	src.write("cp *.sh home\n")
	src.write("tar cvf home.tar home\n")
	src.write("cd ..\n")
	src.write("tar cvf logresults.tar logresults\n")
	src.write("\n")
	src.close()

