def writesubbond(i,datafile):
	src = file('Subbond.sh', "w")
	src.write("#!/bin/tcsh\n")
	src.write("#PBS -l walltime=4:00:00\n")
	src.write("#PBS -l nodes=1:ppn=16\n")
	src.write("#PBS -N %s \n" %i)
	a=findqueue(14400,16)
	while(a):
		if(a=='debug' or a=='ncn' or a=='prism' or a=='standby' or a=='strachan'):
			break
		a=findqueue(14400,16)
	src.write("#PBS -q %s\n" %a)
	src.write("\n")
	src.write("set echo\n")
	src.write("\n")
	src.write("cd $PBS_O_WORKDIR\n")
	src.write("\n")
	src.write("unzip bond.zip\n")
	src.write("cp x.bond bond\n")
	src.write("cp *.data bond\n")
	src.write("cp *.reax bond\n")
	src.write("cd bond\n")
	src.write("cp End_R*.data x.data\n")
	src.write("module load lammps/15Feb16_impi-5.1.2.150\n")
	src.write("mpirun -np 16 lmp < findllmolid.in\n")
	src.write("\n")
	src.write("cp Pan.1.dump x.dump\n")
	src.write("cp %s x.data\n" %datafile)
	src.write("module load lammps/15Feb16_impi-5.1.2.150\n")
	src.write("mpirun -np 16 lmp < findllmolid.in\n")
	src.write("\n")
	src.write("cp Pan.1.dump y.dump\n")
	src.write("module load matlab\n")
	src.write("matlab < newrerun.m > result.m\n")
	src.write("\n")
	src.write("mkdir home\n")
	src.write("cp *.png home\n")
	src.write("cp *file*.txt home\n")
	src.write("cp *.in home\n")
	src.write("cp ?.dump home\n")
	src.write("tar cvf home.tar home\n")
	src.write("matlab < newdataread.m > result.m\n")
	src.write("\n")
	src.write("mkdir structure\n")
	src.write("cp *.data structure\n")
	src.write("cp *.py structure\n")
	src.write("cp *.reax structure\n")
	src.write("cd structure\n")
	src.write("python strsub.py > states.out\n")
	src.write("\n")
	src.close()

